name: Zone
options:
  bundleIdPrefix: com.pengdengke
configs:
  Debug: debug
  Release: release
packages:
  ZoneCore:
    path: .
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  Zone:
    type: application
    platform: macOS
    sources:
      - App/Sources
    dependencies:
      - package: ZoneCore
        product: ZoneCore
